package com.linngdu664.bsf.util;

public enum SnowballType {
    SMOOTH,
    COMPACTED,
    STONE,
    GLASS,
    IRON,
    GOLD,
    OBSIDIAN,
    EXPLOSIVE,
    ICE,
    SPECTRAL,
    TRACKING_PLAYER,
    TRACKING_PLAYER_DAMAGE,
    TRACKING_PLAYER_EXPLOSIVE,
    TRACKING_MONSTER,
    TRACKING_MONSTER_DAMAGE,
    TRACKING_MONSTER_EXPLOSIVE,
    REPULSION_SNOWBALL,
    REPULSION_MONSTER,
    GRAVITY_SNOWBALL,
    GRAVITY_MONSTER,
    BLACKHOLE_PLAYER,
    BLACKHOLE_MONSTER
}
