package com.linngdu664.bsf.util;

public enum TankType {
    COMPACTED,
    STONE,
    GLASS,
    IRON,
    GOLD,
    OBSIDIAN,
    EXPLOSIVE,
    ICE,
    SPECTRAL,
    TRACKING_PLAYER,
    TRACKING_PLAYER_DAMAGE,
    TRACKING_PLAYER_EXPLOSIVE,
    TRACKING_MONSTER,
    TRACKING_MONSTER_DAMAGE,
    TRACKING_MONSTER_EXPLOSIVE,
    REPULSION_PROJECTILE,
    REPULSION_MONSTER,
    GRAVITY_PROJECTILE,
    GRAVITY_MONSTER,
    BLACK_HOLE,
}
